export default {
  // Screens
  INIT: 'APP.INIT',
  LOGIN: 'APP.LOGINSCREEN',
  SIGNUP: 'APP.SIGNUPSCREEN',
  HELP: 'APP.HELPSCREEN',
  MAIN: 'APP.MAINSCREEN',
  PROFILE_EDIT: 'APP.PROFILE_EDIT',
  TRIBES: 'APP.TRIBES',
  TRIBE: 'APP.TRIBE',
  INVITES: 'APP.INVITES',
  SCAN: 'APP.SCANSCREEN',
  LOCALSCAN: 'APP.LOCALSCANSCREEN',
  REGISTER: 'APP.REGISTERSCREEN',
  MAP: 'APP.MAPSCREEN',
  GARAGE: 'APP.GARAGE',
  JOYSTICK: 'APP.JOYSTICK',

  // Modals
  USER_SELECT: 'APP.USER_SELECT',
  CREATE_TRIBE: 'APP.CREATE_TRIBE',

  // Light Boxes
  NOTIFICATION: 'APP.NOTIFICATION',
  MESSAGEBOX: 'APP.MESSAGEBOX',
  LOADING: 'APP.LOADINGSCREEN',
  BLELOGIN: 'APP.BLELOGINSCREEN',
  CONTROL: 'APP.CONTROLSCREEN',
  REGISTER_PROCESS: 'APP.REGISTER_PROCESS',

  // Nav Bar
  NAVBUTTON: 'APP.CUSTOMNAVBUTTON',
  NAVBAR_TRIBE: 'APP.NAVBAR_TRIBE',
  NAVBAR_INVITE: 'APP.NAVBAR_INVITE',
  NAVBACK: 'APP.NAVBACK',
  NAVHAMBURGER: 'APP.NAVHAMBURGER',
  NAVSEARCH: 'APP.NAVSEARCH',
  NAVEDIT: 'APP.NAVEDIT',
  ALERTBACK: 'APP.ALERTBACK',

  // Menu
  PROFILE: 'APP.PROFILEDRAWER',
};
